apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:p7akkFgJj0oHUzZT71B953SK3rxk/ZiG7nn/Ck31Mn2r+uNCxA==,iv:p8/VGtCK+ivD5frw0yWy+70VCBpQdhrmMFDIQmVIeVU=,tag:sImOx49f2nsjc2KuHuZVog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j565yjpyf80z8aqzgf8fsm0da3w35agskydlnle3km5w4h0mgvyshc37qe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMVU5bU5MS0syb1VDVnZY
            MlpFREhBUCtObXc5QmhjM3MrUWFhNStDa1M4CjdqYWRZRVpvQUJDVjBhWDNORWlm
            aDQrRndCaTB4THA4NS9PcXcxc3pOVW8KLS0tIGI5QUxqN2dqeHF2YjdRUDY2bnF5
            eDJjMXdxSklQbWIwV0JxTjB5WCt4QkkKMSVFiuQwq0lteYEzPfKT7z4hLLIPYxUl
            7mYPvdDcquLj/JZRYkoTKoMmMO7Jner0t3ZdiPuv6rLH5iTO3aZLXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T22:50:39Z"
    mac: ENC[AES256_GCM,data:glF+/CEkVmk9WLY7knWJpDbXHNJJ3MNdApai6MRvPcQB3yIEaF1gaRXUCqxYjyucLbHQMquYFgWPI+CP9a5EBbY2GrBn41e8kqGemWfcdsrmAammxoARC5TzAcz32tnTRFC1eGDk/ssQDahUCC4q5aLQh6B8SOOLfmRApyMh9uk=,iv:pvorF/ehHjitYN/3f0Y7vd4lXzFB9bg6mDQXXsMJb/A=,tag:U75SHkLliYt4Wb48WNG7Kg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
