---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  OPENSHIFT_DIR: "{{.ROOT_DIR}}/openshift"

includes:
  flux: .taskfiles/Flux

tasks:
  default:
    silent: true
    cmd: task -l
