---
apiVersion: automationhub.ansible.com/v1beta1
kind: AutomationHub
metadata:
  name: automation-hub
spec:
  ingress_type: Route
  ingress_annotations: |
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-production
  route_host: "hub.${SECRET_DOMAIN}"
  hostname: "hub.${SECRET_DOMAIN}"
  admin_user: ansible
  admin_password_secret: automation-hub-secret
  db_fields_encryption_secret: automation-hub-secret
  postgres_configuration_secret: automation-hub-secret
  object_storage_s3_secret: automation-hub-secret
  pulp_settings:
    aws_s3_endpoint_url: "https://s3.ario.casa"
