---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: automation-hub
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: automation-hub-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_DB_NAME: pulp
        POSTGRES_USERNAME: "{{ .HUB_POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ .HUB_POSTGRES_PASSWORD }}"
        POSTGRES_SSLMODE: prefer

        s3-access-key-id: "{{ .SECRET_MINIO_ACCESS_KEY }}"
        s3-secret-access-key: "{{ .SECRET_MINIO_SECRET_KEY }}"
        s3-bucket-name: "automation-hub"
        s3-region: "us-east-1"

        password: "{{ .HUB_ADMIN_PASSWORD }}"
        secret_key: "{{ .HUB_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: automation-hub
