---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: external-postgres-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        host: postgres-rw.database.svc.cluster.local
        port: "5432"
        database: pulp
        username: "{{ .HUB_POSTGRES_USER }}"
        password: "{{ .HUB_POSTGRES_PASSWORD }}"
        sslmode: prefer
        type: unmanaged
  dataFrom:
    - extract:
        key: automation-hub
