---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: s3-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        s3-access-key-id: "{{ .SECRET_MINIO_ACCESS_KEY }}"
        s3-secret-access-key: "{{ .SECRET_MINIO_SECRET_KEY }}"
        s3-bucket-name: "automation-hub"
        s3-region: "us-east-1"
  dataFrom:
    - extract:
        key: automation-hub
