---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vault
spec:
  host: "vault.${SECRET_DOMAIN}"
  to:
    kind: Service
    name: vault
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
