apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:8x4yZ4HBEDYsulR9cqN+LExxKKVvy4k7PEav70F2q+g=,iv:Fc3Z89PTQpCyGknBl960baozM6Ow5dgvPUzHKjqvkRk=,tag:H+1Mdlsnl4JYEmhhbWupGw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ZDLetgMcINkPPZD5UHw=,iv:2H/RZwYwGHko96eAytPlcwz+dI0OuU1q0xr2oZ96BbU=,tag:CQClc5Ql5hrIT75/r9irlA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:wTyzhwEPgDDF3XWfEaWn/Q==,iv:DuB9PtjDdYUkrthsUvBSGyW/ym+OKa81Ny94fEoov/Q=,tag:dq2dCoAcpMsK+gKPIR1gtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j565yjpyf80z8aqzgf8fsm0da3w35agskydlnle3km5w4h0mgvyshc37qe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNTRRRHRuTzZURUtqbnN6
            OG5xU29xRW50NlQ5alBvSTd5N1k3V0locUY0CllNN2dXYTZsWWR3MUk3dWoyNnpj
            TVAzOE10aVBmKzR3RmdNMEs3SmxFTlEKLS0tIEliV2M2RGxlYzlCOG5sTzk2dVV6
            ZzNOZVhYTjkwNXgwWndFVG1zOVRXUnMKjJgpVnHy5Tz9ZaUyq6tWQQFQhAMeiJit
            ZM2TLDJVWJzRmJvrkQvqoKa/0dWf194v9jHpQeDV3q0CaPIF3Tp3Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T03:54:49Z"
    mac: ENC[AES256_GCM,data:mPf/HQ22sDDm2ozeJ1tUaVDVq0DK8FaA6VL9jGsaPCVzlKcgenuDIT96J79egE28ZKz0Lk2st6PYPfdIT+2/YZhZ8hifTozXe1IO8IW8J9FPEosjpB1iCcJXAzHG3zxKGo7arWYIbmLZ3ktEIuyDT+UvaAM6on6E+WKjcR+dKMs=,iv:b+cq9uKp1mm5ehRGu+qqQOBNLCLYNtUFVTHM/GiE7IA=,tag:7+C8AWj4i56R7HogtoSCbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
