apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:8x4yZ4HBEDYsulR9cqN+LExxKKVvy4k7PEav70F2q+g=,iv:Fc3Z89PTQpCyGknBl960baozM6Ow5dgvPUzHKjqvkRk=,tag:H+1Mdlsnl4JYEmhhbWupGw==,type:str]
    SECRET_CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:VldtW3QYOnnZ/jpwQSaKG8qeofFJTTnpz4aOVFnN8fIILoSa6Q==,iv:PksFuIdi339Q8X6KpDXJqnv/4gP5q+U22tVQx79zjhM=,tag:y7/C2FDpiUNSCJDl3+Rd1w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ZDLetgMcINkPPZD5UHw=,iv:2H/RZwYwGHko96eAytPlcwz+dI0OuU1q0xr2oZ96BbU=,tag:CQClc5Ql5hrIT75/r9irlA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:wTyzhwEPgDDF3XWfEaWn/Q==,iv:DuB9PtjDdYUkrthsUvBSGyW/ym+OKa81Ny94fEoov/Q=,tag:dq2dCoAcpMsK+gKPIR1gtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j565yjpyf80z8aqzgf8fsm0da3w35agskydlnle3km5w4h0mgvyshc37qe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNTRRRHRuTzZURUtqbnN6
            OG5xU29xRW50NlQ5alBvSTd5N1k3V0locUY0CllNN2dXYTZsWWR3MUk3dWoyNnpj
            TVAzOE10aVBmKzR3RmdNMEs3SmxFTlEKLS0tIEliV2M2RGxlYzlCOG5sTzk2dVV6
            ZzNOZVhYTjkwNXgwWndFVG1zOVRXUnMKjJgpVnHy5Tz9ZaUyq6tWQQFQhAMeiJit
            ZM2TLDJVWJzRmJvrkQvqoKa/0dWf194v9jHpQeDV3q0CaPIF3Tp3Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T15:16:48Z"
    mac: ENC[AES256_GCM,data:vnkKhkbh/0KVpWC6Uo4DzQm2JiWuG7o5V57cXVI8tj43XA1qsdvHOO4eS1Qrz0wS6tT4snsMgTS94ntCBGhN4EQCThCHT/RVjTIsIeT+N7y+ZyIc8ATbt9r6p3NXpN2Llw6uTPUg3l4Xw/x8wca1P4RDdN6Y728iHtWNY6FwIyU=,iv:7CQd6mARFh/VQ6EZ5spoe4A7mHznFWW9HzcZbptl3xQ=,tag:VoNkRQTUY2F/BK8HtoMZ5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
