---
apiVersion: eda.ansible.com/v1alpha1
kind: EDA
metadata:
  name: eda-controller
spec:
  ingress_type: Route
  route_host: "eda.${SECRET_DOMAIN}"
  hostname: "eda.${SECRET_DOMAIN}"
  db_fields_encryption_secret: eda-controller-secret
  database:
    database_secret: eda-controller-secret
  admin_user: ansible
  automation_server_url: "https://con.${SECRET_DOMAIN}"
