---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: automation-controller
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: automation-controller-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        host: postgres-rw.database.svc.cluster.local
        port: "5432"
        database: awx
        username: "{{ .AWX_POSTGRES_USER }}"
        password: "{{ .AWX_POSTGRES_PASSWORD }}"
        sslmode: prefer
        type: unmanaged

        secret_key: "{{ .AWX_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: automation-controller
